
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1823:Unused field 'PrizeValue3'.", Justification = "<Pending>", Scope = "member", Target = "~F:Guessanumber.SecondForm.PrizeValue3")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1823:Unused field 'RandomValue2'.", Justification = "<Pending>", Scope = "member", Target = "~F:Guessanumber.SecondForm.RandomValue2")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1823:Unused field 'RandomValue3'.", Justification = "<Pending>", Scope = "member", Target = "~F:Guessanumber.SecondForm.RandomValue3")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Convert.ToInt32(string)' could vary based on the current user's locale settings. Replace this call in 'SecondForm.Buttonresult1to10_Click(object, EventArgs)' with a call to 'Convert.ToInt32(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Guessanumber.SecondForm.Buttonresult1to10_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Convert.ToInt16(string)' could vary based on the current user's locale settings. Replace this call in 'SecondForm.Buttonresult20to40_Click(object, EventArgs)' with a call to 'Convert.ToInt16(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Guessanumber.SecondForm.Buttonresult20to40_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'Convert.ToInt16(string)' could vary based on the current user's locale settings. Replace this call in 'SecondForm.Buttonresult50to100_Click(object, EventArgs)' with a call to 'Convert.ToInt16(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:Guessanumber.SecondForm.Buttonresult50to100_Click(System.Object,System.EventArgs)")]